# -*- coding: utf-8 -*-
"""AutoML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9WXDTyw-vSwuzcz1eqk4oG3vvmOOpY_
"""

!pip install autokeras
!pip install git+https://github.com/keras-team/keras-tuner.git@1.0.2

import pandas as pd
import numpy as np
import tensorflow as tf
import autokeras as ak

from google.colab import drive
drive.mount('/content/drive')
Train = pd.read_csv('/content/drive/MyDrive/datasets/news_train.csv')
Test = pd.read_csv('/content/drive/MyDrive/datasets/news_test.csv')

X = Train.content.values
Y =  Train['info'].values

input_node = ak.TextInput()
output_node = ak.TextToIntSequence()(input_node)
output_node = ak.Embedding()(output_node)
output_node = ak.ConvBlock(separable=True)(output_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(
    inputs=input_node,
    outputs=output_node,
    overwrite=True,
    max_trials=5
    )
clf.fit(X, Y, epochs=5)
model = clf.export_model()

model.summary()

sample_submission = pd.read_csv('/content/drive/MyDrive/datasets/sample_submission.csv')
pred_test = model.predict(Test.content.values)
sample_submission.loc[:,'info'] = np.where(pred_test> 0.5, 1,0).reshape(-1)

sample_submission.loc[:,["id","info"]].to_csv("AutoML.csv", index = False)
sample_submission